Repository code-4-u/beauty-4-u-BE, pull requests merged in 2024-12, with the labels that each got.

#4 feat: 엔티티 추가
  .gitignore
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/Analysis.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/AssociationRecommendation.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingNoti.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingSetting.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/PersonalizedRecommendation.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Faq.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Inform.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Inquiry.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/InquiryReply.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Noti.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/ScheduleInfo.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Template.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/Customer.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/OrderInfo.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/Brand.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/Goods.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/Review.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/SubCategory.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/TopCategory.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionGoods.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionNoti.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionSetting.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/LastRead.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ScrapReply.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Teamspace.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/Dept.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/Job.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserRole.java
  src/main/resources/application.yml
Labels: feat

#7 feat: 시큐리티 추가
  build.gradle
  src/main/java/com/beauty4u/backend/BackendApplication.java
  src/main/java/com/beauty4u/backend/common/common.java
  src/main/java/com/beauty4u/backend/common/exception/CustomException.java
  src/main/java/com/beauty4u/backend/common/exception/CustomExceptionHandler.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/CustomSuccess.java
  src/main/java/com/beauty4u/backend/common/success/CustomSuccessHandler.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
  src/main/java/com/beauty4u/backend/config/AppConfig.java
  src/main/java/com/beauty4u/backend/config/SwaggerConfig.java
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/java/com/beauty4u/backend/security/dto/LoginRequest.java
  src/main/java/com/beauty4u/backend/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
  src/main/java/com/beauty4u/backend/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/beauty4u/backend/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/beauty4u/backend/security/handler/LoginFailureHandler.java
  src/main/java/com/beauty4u/backend/security/handler/LoginSuccessHandler.java
  src/main/java/com/beauty4u/backend/security/util/CustomUserDetailsService.java
  src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
  src/main/resources/application.yml
Labels: feat

#9 feat: 회원 등록 기능 구현 #8
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/command/application/dto/CreateUserRequest.java
  src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/beauty4u/backend/user/command/domain/repository/DeptRepository.java
  src/main/java/com/beauty4u/backend/user/command/domain/repository/JobRepository.java
  src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
  src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRoleRepository.java
  src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
Labels: feat

#12 feat: 공통 응답 유틸 구현
  src/main/java/com/beauty4u/backend/common/exception/CustomException.java
  src/main/java/com/beauty4u/backend/common/exception/CustomExceptionHandler.java
  src/main/java/com/beauty4u/backend/common/response/ApiResponse.java
  src/main/java/com/beauty4u/backend/common/response/ResponseUtil.java
  src/main/java/com/beauty4u/backend/common/success/CustomSuccessHandler.java
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
Labels: feat

#15 feat: MyBatis 설정 추가
  build.gradle
  src/main/java/com/beauty4u/backend/config/MyBatisConfig.java
  src/main/resources/application.yml
Labels: feat

#16 feat: 리프레시 토큰 구현
  src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
  src/main/java/com/beauty4u/backend/config/SwaggerConfig.java
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
  src/main/java/com/beauty4u/backend/security/handler/LoginSuccessHandler.java
  src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
  src/main/resources/application.yml
Labels: feat

#17 feat: 전체 상품 목록 조회, 엘라스틱 서치 로컬 연동
  build.gradle
  src/main/java/com/beauty4u/backend/elasticesearch/ElasticsearchConfig.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/Goods.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/SubCategory.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsQueryDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/application.yml
  src/main/resources/mappers/goods/GoodsMapper.xml
Labels: feat, chore

#18 feat: 상품 조건별 조회, 브랜드 별 조회 구현
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/BrandQueryDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/mapper/goods/GoodsMapper.xml
Labels: feat, chore

#20 feat: mongoDB 연동 및 조회 예시 코드 작성 SSP-64
  build.gradle
  src/main/java/com/beauty4u/backend/BackendApplication.java
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChattingMessage.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/LastRead.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ScrapReply.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Teamspace.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChattingMessageRepository.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChattingMessageController.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/ChattingMessageService.java
  src/main/resources/application.yml
Labels: feat

#21 fix: mappers 폴더 삭제
  src/main/resources/mappers/goods/GoodsMapper.xml
Labels: fix

#24 fix: 상품 조건별 조회 수정
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/mapper/goods/GoodsMapper.xml
Labels: fix

#25 feat: 레디스 연동 및 관련 메서드 구현
  build.gradle
  src/main/java/com/beauty4u/backend/config/redis/RedisConfig.java
  src/main/java/com/beauty4u/backend/config/redis/RedisService.java
  src/main/resources/application.yml
Labels: feat

#30 feat: 레디스 활용 Jwt 로직 구현
  docker-compose.yml
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
  src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
Labels: fix, feat

#33 feat: 회원 목록 조회 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
  src/main/java/com/beauty4u/backend/user/query/dto/UserListResDTO.java
  src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/UserMapper.xml
  src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
Labels: feat, test

#28 feat: 고객 목록 조회 백 기능 구현
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/Customer.java
  src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerFilterRequest.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerGrade.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListResDTO.java
  src/main/java/com/beauty4u/backend/customer/query/mapper/CustomerQueryMapper.java
  src/main/java/com/beauty4u/backend/customer/query/service/CustomerQueryService.java
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/resources/mapper/customerMapper/CustomerMapper.xml
Labels: feat, chore

#35 refactor: 응답 생성 코드 리팩토링
  src/main/java/com/beauty4u/backend/common/response/ApiResponse.java
  src/main/java/com/beauty4u/backend/common/response/ResponseUtil.java
  src/main/java/com/beauty4u/backend/common/success/CustomSuccess.java
  src/main/java/com/beauty4u/backend/common/success/CustomSuccessHandler.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerDetailResDTO.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
Labels: refactor

#36 feat: 고객 상세 조회 백 기능 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
  src/main/java/com/beauty4u/backend/customer/query/mapper/CustomerQueryMapper.java
  src/main/java/com/beauty4u/backend/customer/query/service/CustomerQueryService.java
  src/main/resources/mapper/customerMapper/CustomerMapper.xml
Labels: feat

#39 feat: 엘라스틱 서치 구현 완료 #6
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchConfig.java
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/application.yml
Labels: feat

#40 fix: 시큐리티 수정
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/java/com/beauty4u/backend/security/filter/JwtFilter.java
Labels: fix

#41 fix: 엘라스틱서치 비활성화 조건부 설정 추가
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/application.yml
Labels: fix

#44 chore: 이메일 전송 관련 설정
  build.gradle
  src/main/java/com/beauty4u/backend/common/util/MailUtil.java
  src/main/resources/application.yml
Labels: feat, chore

#45 feat: 아이디 찾기 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/command/application/dto/LoginUserReqDTO.java
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
  src/main/java/com/beauty4u/backend/user/query/dto/FindUserCodeReqDTO.java
  src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: feat, chore

#50 feat: 상품 리뷰 조회
  src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/ReviewQueryDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/ReviewQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
  src/main/resources/mapper/goods/ReviewMapper.xml
Labels: feat

#48 refactor: 아이디 찾기 메서드 위치 수정
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
  src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
  src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
  src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: refactor

#53 feat: 내 정보 조회 구현
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
  src/main/java/com/beauty4u/backend/user/query/dto/FindUserDetailResDTO.java
  src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: feat

#55 feat: 비밀번호 수정 구현
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/command/application/dto/UpdateUserPasswordReqDTO.java
  src/main/java/com/beauty4u/backend/user/command/application/service/UserCommandService.java
Labels: feat

#61 feat: 공지사항 등록 구현
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
  src/main/java/com/beauty4u/backend/common/aggregate/StatusType.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inform/command/application/controller/InformCommandController.java
  src/main/java/com/beauty4u/backend/inform/command/application/dto/CreateInformReqDTO.java
  src/main/java/com/beauty4u/backend/inform/command/application/service/InformCommandService.java
  src/main/java/com/beauty4u/backend/inform/command/domain/aggregate/Inform.java
  src/main/java/com/beauty4u/backend/inform/command/domain/repository/InformRepository.java
  src/main/java/com/beauty4u/backend/inform/command/domain/service/InformDomainService.java
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
Labels: feat, refactor

#69 feat: 공지사항 목록 조회 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inform/query/controller/InformQueryController.java
  src/main/java/com/beauty4u/backend/inform/query/dto/InformListResDTO.java
  src/main/java/com/beauty4u/backend/inform/query/mapper/InformQueryMapper.java
  src/main/java/com/beauty4u/backend/inform/query/service/InformQueryService.java
  src/main/resources/mapper/inform/InformMapper.xml
Labels: feat

#73 feat: QnA 질문 등록 구현
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/Noti.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/dto/CreateQnaReqDTO.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryCommandService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryRepository.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
Labels: feat, refactor

#85 feat: 템플릿 기본 기능 구현
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingSetting.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionSetting.java
  src/main/java/com/beauty4u/backend/template/command/application/controller/TemplateCommandController.java
  src/main/java/com/beauty4u/backend/template/command/application/dto/CreateTemplateReqDTO.java
  src/main/java/com/beauty4u/backend/template/command/application/dto/UpdateTemplateReqDTO.java
  src/main/java/com/beauty4u/backend/template/command/application/service/TemplateCommandService.java
  src/main/java/com/beauty4u/backend/template/command/domain/aggregate/Template.java
  src/main/java/com/beauty4u/backend/template/command/domain/repository/TemplateRepository.java
  src/main/java/com/beauty4u/backend/template/command/domain/service/TemplateDomainService.java
  src/main/java/com/beauty4u/backend/template/query/controller/TemplateQueryController.java
  src/main/java/com/beauty4u/backend/template/query/dto/TemplateQueryDTO.java
  src/main/java/com/beauty4u/backend/template/query/mapper/TemplateQueryMapper.java
  src/main/java/com/beauty4u/backend/template/query/service/TemplateQueryService.java
  src/main/resources/mapper/template/TemplateMapper.xml
Labels: feat, chore

#68 feat: 템플릿 목록 조회 기능 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
Labels: feat, chore

#81 feat: QnA 답변 수정 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryReplyCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyCommandService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/InquiryReplyRepository.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryReplyDomainService.java
Labels: feat, refactor

#89 feat: 템플릿 삭제 기능 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/template/command/application/controller/TemplateCommandController.java
  src/main/java/com/beauty4u/backend/template/command/application/service/TemplateCommandService.java
  src/main/java/com/beauty4u/backend/template/command/domain/aggregate/Template.java
  src/main/java/com/beauty4u/backend/template/command/domain/service/TemplateDomainService.java
Labels: feat, chore

#90 feat: 고객 구매 이력 조회 백 기능 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/Customer.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/CustomerGrade.java
  src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListResDTO.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerOrderInfoListResDTO.java
  src/main/java/com/beauty4u/backend/customer/query/dto/OrderHistoryFilterDTO.java
  src/main/java/com/beauty4u/backend/customer/query/mapper/CustomerQueryMapper.java
  src/main/java/com/beauty4u/backend/customer/query/service/CustomerQueryService.java
  src/main/resources/mapper/customerMapper/CustomerMapper.xml
Labels: feat, chore

#91 refactor: YnType 공통 enum 분리
  src/main/java/com/beauty4u/backend/common/aggregate/YnType.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/Customer.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/CustomerGrade.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/OrderInfo.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerFilterRequest.java
  src/main/java/com/beauty4u/backend/inform/command/application/controller/InformCommandController.java
  src/main/java/com/beauty4u/backend/inform/command/application/service/InformService.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryReplyCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/dto/QnaReqDTO.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyService.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
  src/main/java/com/beauty4u/backend/noti/command/application/controller/NotiCommandController.java
  src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/Noti.java
  src/main/java/com/beauty4u/backend/template/command/application/controller/TemplateCommandController.java
  src/main/java/com/beauty4u/backend/template/command/application/dto/TemplateReqDTO.java
  src/main/java/com/beauty4u/backend/template/command/application/dto/UpdateTemplateReqDTO.java
  src/main/java/com/beauty4u/backend/template/command/application/service/TemplateCommandService.java
  src/main/java/com/beauty4u/backend/template/command/application/service/TemplateService.java
  src/main/java/com/beauty4u/backend/template/command/domain/aggregate/Template.java
  src/main/java/com/beauty4u/backend/template/command/domain/service/TemplateDomainService.java
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/command/application/service/UserService.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/Dept.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/Job.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserRole.java
Labels: feat, refactor

#93 refactor: BaseEntity 구현 및 ddl 수정
  src/main/java/com/beauty4u/backend/BackendApplication.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/Analysis.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/AssociationRecommendation.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingNoti.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingSetting.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/PersonalizedRecommendation.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/ScheduleInfo.java
  src/main/java/com/beauty4u/backend/common/aggregate/entity/BaseEntity.java
  src/main/java/com/beauty4u/backend/common/aggregate/entity/CreatedTimeEntity.java
  src/main/java/com/beauty4u/backend/common/aggregate/entity/CreatedUpdatedTimeEntity.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/Customer.java
  src/main/java/com/beauty4u/backend/customer/command/domain/aggregate/OrderInfo.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListResDTO.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerOrderInfoListResDTO.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/Brand.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/Goods.java
  src/main/java/com/beauty4u/backend/goods/command/domain/aggregate/Review.java
  src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/BrandQueryDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/CategoryDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsQueryDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/ReviewQueryDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/SubCategoryDTO.java
  src/main/java/com/beauty4u/backend/inform/command/domain/aggregate/Inform.java
  src/main/java/com/beauty4u/backend/inform/query/dto/InformDetailResDTO.java
  src/main/java/com/beauty4u/backend/inform/query/dto/InformListResDTO.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Inquiry.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
  src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/Noti.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionGoods.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionNoti.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionSetting.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/LastRead.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ScrapReply.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Teamspace.java
  src/main/java/com/beauty4u/backend/template/command/domain/aggregate/Template.java
  src/main/java/com/beauty4u/backend/template/query/dto/TemplateQueryDTO.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/beauty4u/backend/user/query/dto/UserListResDTO.java
  src/main/resources/mapper/customer/CustomerMapper.xml
  src/main/resources/mapper/goods/GoodsMapper.xml
  src/main/resources/mapper/goods/ReviewMapper.xml
  src/main/resources/mapper/inform/InformMapper.xml
  src/main/resources/mapper/template/TemplateMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
Labels: feat, refactor

#95 refactor: 고객 목록 조회 응답 DTO 수정
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListResDTO.java
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/resources/mapper/customer/CustomerMapper.xml
Labels: refactor

#98 feat: QnA 목록 조회 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/query/controller/InquiryQueryController.java
  src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryListResDTO.java
  src/main/java/com/beauty4u/backend/inquiry/query/mapper/InquiryQueryMapper.java
  src/main/java/com/beauty4u/backend/inquiry/query/service/InquiryQueryService.java
  src/main/resources/mapper/inquiry/InquiryMapper.xml
Labels: feat

#102 feat: FAQ 등록 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/FaqCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/dto/FaqReqDTO.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/FaqService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/repository/FaqRepository.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/FaqDomainService.java
Labels: feat

#104 feat: FAQ 수정 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/FaqCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/FaqService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/FaqDomainService.java
Labels: fix, feat

#106 feat: FAQ 삭제 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/FaqCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/FaqService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/Faq.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/FaqDomainService.java
Labels: feat

#111 feat: 마케팅 알림 설정 등록 구현중
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/Analysis.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/AnalysisKind.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingNoti.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/MarketingSetting.java
  src/main/java/com/beauty4u/backend/common/aggregate/SettingChannelType.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/marketing/command/application/controller/MarketingSettingCommandController.java
  src/main/java/com/beauty4u/backend/marketing/command/application/dto/MarketingSettingReqDTO.java
  src/main/java/com/beauty4u/backend/marketing/command/application/service/MarketingSettingService.java
  src/main/java/com/beauty4u/backend/marketing/command/domain/aggregate/MarketingSetting.java
  src/main/java/com/beauty4u/backend/marketing/command/domain/repository/MarketingSettingRepository.java
  src/main/java/com/beauty4u/backend/marketing/command/domain/service/MarketingSettingDomainService.java
Labels: feat, chore

#109 feat: AWS S3 설정 및 기본 CRUD 틀 작성
  build.gradle
  src/main/java/com/beauty4u/backend/config/S3Config.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ScarpCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamSpaceCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/CreateFolderRequest.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/scrap/CreateScrapRequest.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/teamspace/CreateTeamspaceRequest.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ScrapService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/TeamSpaceService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/FolderStatus.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ScrapStatus.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMessageRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/FolderRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ScrapRepository.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamSpaceQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/folder/FolderResponse.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/teamspace/TeamSpaceResponse.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/TeamSpaceQueryService.java
  src/main/resources/application.yml
Labels: feat, chore

#114 feat: 깃허브 액션 추가
  .github/workflows/deploy.yml
Labels: feat

#107 refactor: 고객 도메인 조회 페이징 처리를 위한 로직 추가
  src/main/java/com/beauty4u/backend/customer/query/controller/CustomerQueryController.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListDTO.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerListResDTO.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerOrderInfoListDTO.java
  src/main/java/com/beauty4u/backend/customer/query/dto/CustomerOrderInfoListResDTO.java
  src/main/java/com/beauty4u/backend/customer/query/mapper/CustomerQueryMapper.java
  src/main/java/com/beauty4u/backend/customer/query/service/CustomerQueryService.java
  src/main/resources/mapper/customer/CustomerMapper.xml
Labels: fix, chore, refactor

#116 feat: FAQ 목록 조회 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/query/controller/FaqQueryController.java
  src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqListResDTO.java
  src/main/java/com/beauty4u/backend/inquiry/query/mapper/FaqQueryMapper.java
  src/main/java/com/beauty4u/backend/inquiry/query/service/FaqQueryService.java
  src/main/resources/mapper/inquiry/FaqMapper.xml
Labels: feat

#118 feat: FAQ 상세 조회 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/query/controller/FaqQueryController.java
  src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqDetailResDTO.java
  src/main/java/com/beauty4u/backend/inquiry/query/mapper/FaqQueryMapper.java
  src/main/java/com/beauty4u/backend/inquiry/query/service/FaqQueryService.java
  src/main/resources/mapper/inquiry/FaqMapper.xml
Labels: feat

#123 feat: 엘라스틱 서치 리뷰 조회 구현
  src/main/java/com/beauty4u/backend/elasticsearch/BaseSearchDocument.java
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchConfig.java
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/ReviewDocument.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/ReviewSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
  src/main/resources/application.yml
  src/main/resources/mapper/goods/ReviewMapper.xml
Labels: feat, chore

#127 feat: 알림 조회 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/noti/command/application/controller/NotiCommandController.java
  src/main/java/com/beauty4u/backend/noti/command/application/service/NotiService.java
  src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/Noti.java
  src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
  src/main/java/com/beauty4u/backend/noti/command/domain/repository/NotiRepository.java
  src/main/java/com/beauty4u/backend/noti/command/domain/repository/SseRepository.java
  src/main/java/com/beauty4u/backend/noti/command/domain/service/NotiDomainService.java
  src/main/java/com/beauty4u/backend/noti/query/controller/NotiQueryController.java
  src/main/java/com/beauty4u/backend/noti/query/dto/NotiListResDTO.java
  src/main/java/com/beauty4u/backend/noti/query/mapper/NotiQueryMapper.java
  src/main/java/com/beauty4u/backend/noti/query/service/NotiQueryService.java
  src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
  src/main/resources/mapper/noti/NotiMapper.xml
  src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
Labels: feat

#130 refactor, test: 회원 등록 리팩토링 및 테스트 구현
  src/main/java/com/beauty4u/backend/user/command/application/dto/CreateUserReqDTO.java
  src/main/java/com/beauty4u/backend/user/command/application/service/UserService.java
  src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
  src/test/java/com/beauty4u/backend/user/command/application/service/UserServiceTest.java
Labels: refactor, test

#131 refactor: 공지사항 조회 필터링, 정렬 조건 추가
  src/main/java/com/beauty4u/backend/inform/query/controller/InformQueryController.java
  src/main/java/com/beauty4u/backend/inform/query/dto/InformFilterDTO.java
  src/main/java/com/beauty4u/backend/inform/query/dto/InformListDTO.java
  src/main/java/com/beauty4u/backend/inform/query/dto/InformListResDTO.java
  src/main/java/com/beauty4u/backend/inform/query/mapper/InformQueryMapper.java
  src/main/java/com/beauty4u/backend/inform/query/service/InformQueryService.java
  src/main/resources/mapper/inform/InformMapper.xml
Labels: feat, refactor

#133 refactor: 비밀번호 수정 리팩토링
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/user/command/application/dto/UpdateUserPasswordReqDTO.java
  src/main/java/com/beauty4u/backend/user/command/application/service/UserService.java
  src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
Labels: refactor

#137 feat: 엘라스틱서치 설정값 추가
  Dockerfile
  docker-compose.yml
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/ReviewSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
  src/main/resources/application.yml
  src/main/resources/elasticsearch/mappings/mappings.json
  src/main/resources/elasticsearch/settings/settings.json
Labels: feat, chore

#135 feat: 카프카 설정 및 리팩토링
  build.gradle
  docker-compose.yml
  src/main/java/com/beauty4u/backend/config/WebSocketConfig.java
  src/main/java/com/beauty4u/backend/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/beauty4u/backend/config/kafka/KafkaProducerConfig.java
  src/main/java/com/beauty4u/backend/config/mongo/MongoConfig.java
  src/main/java/com/beauty4u/backend/config/s3/S3Config.java
  src/main/java/com/beauty4u/backend/config/webSocket/SocketTextHandler.java
  src/main/java/com/beauty4u/backend/config/webSocket/StompHandler.java
  src/main/java/com/beauty4u/backend/config/webSocket/WebSocketConfig.java
  src/main/java/com/beauty4u/backend/config/zoneDateTime/StringToZonedDateTimeConverter.java
  src/main/java/com/beauty4u/backend/config/zoneDateTime/ZonedDateTimeToStringConverter.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamSpaceCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageRequest.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/CreateFolderReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/scrap/CreateScrapReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/teamspace/CreateTeamspaceReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/teamspace/CreateTeamspaceRequest.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/TeamSpaceService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Teamspace.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMessageRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/FolderRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ScrapRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamSpaceRepository.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamSpaceQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatMessage/ChatMessageResDto.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/teamspace/TeamSpaceUserInfoDto.java
  src/main/java/com/beauty4u/backend/teamspace/query/mapper/TeamSpaceQueryMapper.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/ChatQueryService.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/TeamSpaceQueryService.java
  src/main/resources/mapper/teamSpace/TeamSpaceMapper.xml
  src/test/java/com/beauty4u/backend/BackendApplicationTests.java
Labels: feat

#138 fix: 팀스페이스 레포지토리 수정
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamSpaceRepository.java
Labels: fix

#140 refactor: 회원 등록 기능 리팩토링
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/command/application/dto/CreateUserReqDTO.java
  src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
  src/main/java/com/beauty4u/backend/user/query/dto/DeptResDTO.java
  src/main/java/com/beauty4u/backend/user/query/dto/JobResDTO.java
  src/main/java/com/beauty4u/backend/user/query/dto/RoleResDTO.java
  src/main/java/com/beauty4u/backend/user/query/dto/UserListResDTO.java
  src/main/java/com/beauty4u/backend/user/query/mapper/DeptQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/mapper/JobQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/mapper/RoleQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/DeptMapper.xml
  src/main/resources/mapper/user/JobMapper.xml
  src/main/resources/mapper/user/RoleMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
  src/test/java/com/beauty4u/backend/user/command/application/service/UserServiceTest.java
Labels: feat, refactor, test

#142 feat: 회원 정보 수정 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/user/command/application/controller/UserCommandController.java
  src/main/java/com/beauty4u/backend/user/command/application/dto/UpdateUserReqDTO.java
  src/main/java/com/beauty4u/backend/user/command/application/service/UserService.java
  src/main/java/com/beauty4u/backend/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
Labels: feat

#143 feat: 분석 대시 보드 데이터 조회 기능
  src/main/java/com/beauty4u/backend/analysis/query/controller/AnalysisQueryController.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/request/AnalysisCircleGraphReqDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/request/AnalysisGradeBrandCircleReqDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/request/AnalysisGradeCircleReqDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/request/AnalysisGradeStickGraphReqDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/request/AnalysisStickGraphProductReqDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/request/AnalysisStickGraphReqDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisAgeGroupRadioResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisAgeSalesByBrandProductResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisAgeSalesByBrandResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisAgeSalesRadioResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisGradeByBrandProductResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisGradeByBrandResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisGradeGroupRadioResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisGradeSalesByBrandProductResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisGradeSalesByBrandResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisGradeSalesRadioDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisPurchasesByAgeResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisPurchasesByBrandProductResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisPurchasesByBrandResDTO.java
  src/main/java/com/beauty4u/backend/analysis/query/mapper/AnalysisQueryMapper.java
  src/main/java/com/beauty4u/backend/analysis/query/service/AnalysisQueryService.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/resources/mapper/analysis/analysisMapper.xml
  src/test/java/com/beauty4u/backend/analysis/query/service/AnalysisQueryServiceTest.java
Labels: feat

#145 feat: 엘라스틱 서치 도커 연결
  build.gradle
  docker-compose.yml
  logstash/pipeline/logstash.conf
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/ReviewSortDTO.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/ReviewSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/ReviewQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/main/resources/mapper/goods/ReviewMapper.xml
Labels: feat

#147 feat: 일정 등록, 수정, 삭제 구현
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/FileInfo.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/aggregate/ScheduleInfo.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/beauty4u/backend/schedule/command/application/dto/ScheduleReqDTO.java
  src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleInfo.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleType.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/repository/ScheduleRepository.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/service/ScheduleDomainService.java
  src/main/java/com/beauty4u/backend/schedule/query/controller/ScheduleQueryController.java
  src/main/java/com/beauty4u/backend/schedule/query/dto/ScheduleListResDTO.java
  src/main/java/com/beauty4u/backend/schedule/query/mapper/ScheduleQueryMapper.java
  src/main/java/com/beauty4u/backend/schedule/query/service/ScheduleQueryService.java
  src/main/resources/mapper/schedule/ScheduleMapper.xml
Labels: feat, refactor

#149 fix: logback 의존성 적용 되도록 수정
  src/main/resources/logback.xml
Labels: fix

#151 refactor: FAQ 목록 조회 리팩토링
  src/main/java/com/beauty4u/backend/inquiry/query/controller/FaqQueryController.java
  src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqFilterReqDTO.java
  src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqListDTO.java
  src/main/java/com/beauty4u/backend/inquiry/query/dto/FaqListResDTO.java
  src/main/java/com/beauty4u/backend/inquiry/query/mapper/FaqQueryMapper.java
  src/main/java/com/beauty4u/backend/inquiry/query/service/FaqQueryService.java
  src/main/resources/mapper/inquiry/FaqMapper.xml
Labels: refactor

#152 refactor: 공지사항, 파일 s3 구현
  src/main/java/com/beauty4u/backend/basesystem/command/application/controller/FileController.java
  src/main/java/com/beauty4u/backend/basesystem/command/application/dto/FileDTO.java
  src/main/java/com/beauty4u/backend/basesystem/command/application/dto/FileDeleteReqDTO.java
  src/main/java/com/beauty4u/backend/basesystem/command/application/dto/FileSaveReqDTO.java
  src/main/java/com/beauty4u/backend/basesystem/command/application/service/FileService.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/repository/FileRepository.java
  src/main/java/com/beauty4u/backend/basesystem/command/domain/service/FileDomainService.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/common/util/S3ImageUtil.java
  src/main/java/com/beauty4u/backend/inform/command/application/controller/InformCommandController.java
  src/main/java/com/beauty4u/backend/inform/command/application/dto/InformDTO.java
  src/main/java/com/beauty4u/backend/inform/command/application/dto/UpdateInformViewcount.java
  src/main/java/com/beauty4u/backend/inform/command/application/service/InformService.java
  src/main/java/com/beauty4u/backend/inform/command/domain/aggregate/Inform.java
  src/main/java/com/beauty4u/backend/inform/command/domain/service/InformDomainService.java
  src/main/java/com/beauty4u/backend/inform/query/dto/InformDetailResDTO.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/dto/InquiryDTO.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
  src/main/resources/application.yml
  src/main/resources/mapper/inform/InformMapper.xml
Labels: feat, refactor

#158 feat: 해당 브랜드 상품 조회 기능
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/ReviewDocument.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/application.yml
  src/main/resources/elasticsearch/mappings/mappings.json
  src/main/resources/logback-spring.xml
  src/main/resources/mapper/goods/GoodsMapper.xml
Labels: feat, chore

#160 feat: 프로모션 목록 조회 백 기능 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionListReqDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionDetailResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
  src/main/resources/mapper/promotion/PromotionMapper.xml
Labels: feat

#162 feat: 프로모션 수정 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
  src/main/resources/mapper/promotion/PromotionMapper.xml
Labels: feat, chore

#164 feat: 프로모션 삭제 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
  src/main/resources/mapper/promotion/PromotionMapper.xml
Labels: feat

#169 feat: 폴더 수정 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/UpdateFolderDTO.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
Labels: feat

#173 feat: 폴더 삭제 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/FolderCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Scrap.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
Labels: feat

#190 feat: 액세스토큰에 부서, 직급, 회원이름 추가
  src/main/java/com/beauty4u/backend/security/util/CustomUserDetails.java
  src/main/java/com/beauty4u/backend/security/util/CustomUserDetailsService.java
  src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
Labels: feat

#193 feat: 액세스토큰에 부서코드 추가
  src/main/java/com/beauty4u/backend/security/util/CustomUserDetails.java
  src/main/java/com/beauty4u/backend/security/util/CustomUserDetailsService.java
  src/main/java/com/beauty4u/backend/security/util/JwtUtil.java
Labels: refactor

#183 feat: 프로모션 종류 저장 기능 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionTypeController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionTypeDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionTypeService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionType.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionTypeRepository.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionTypeDomainService.java
  src/main/resources/mapper/promotion/PromotionMapper.xml
Labels: fix, feat

#195 feat: 프로모션 종류 목록 조회 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeListDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeFilterDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionTypeQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionTypeQueryService.java
  src/main/resources/mapper/promotion/PromotionTypeMapper.xml
Labels: feat

#199 feat: 프로모션 기본 리팩토링
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionReqDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionDetailResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
  src/main/resources/mapper/promotion/PromotionMapper.xml
  src/main/resources/mapper/promotion/PromotionTypeMapper.xml
Labels: refactor

#202 feat: 프로모션 상품 등록 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/goods/command/domain/repository/GoodsRepository.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionGoodsController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionTypeController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/SaveGoodsDiscountDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionGoodsDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionGoodsReqDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionGoodsService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/Promotion.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionGoodsRepository.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionGoodsDomainService.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeFilterDTO.java
  src/main/resources/mapper/promotion/PromotionTypeMapper.xml
Labels: fix, feat

#204 feat: 프로모션 적용 상품 삭제 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionGoodsController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/DeletePromotionGoodsReqDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionGoodsService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionGoodsDomainService.java
Labels: feat

#209 feat: 프로모션 상품 목록 조회 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionGoodsQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsListFilterDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsListResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionGoodsQueryService.java
  src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
Labels: feat

#211 feat: 특정 상품에 대한 프로모션 정보 리스트 조회 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionGoodsQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsCommonInfoFilterDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsCommonInfoResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsSalesDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionGoodsQueryService.java
  src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
Labels: feat

#214 feat: 제품의 전년 대비 같은 월 비교 백 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsSalesQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsSalesFilterDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsSalesResDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsSalesQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsSalesQueryService.java
  src/main/resources/mapper/goods/GoodsSalesMapper.xml
Labels: feat

#216 refactor: 파일 업로드 리팩토링
  src/main/java/com/beauty4u/backend/file/command/application/controller/FileController.java
  src/main/java/com/beauty4u/backend/file/command/application/dto/FileDTO.java
  src/main/java/com/beauty4u/backend/file/command/application/dto/FileDeleteReqDTO.java
  src/main/java/com/beauty4u/backend/file/command/application/dto/FileSaveReqDTO.java
  src/main/java/com/beauty4u/backend/file/command/application/service/FileService.java
  src/main/java/com/beauty4u/backend/file/command/domain/aggregate/FileInfo.java
  src/main/java/com/beauty4u/backend/file/command/domain/repository/FileRepository.java
  src/main/java/com/beauty4u/backend/file/command/domain/service/FileDomainService.java
  src/main/java/com/beauty4u/backend/inform/command/application/service/InformService.java
  src/main/java/com/beauty4u/backend/inform/query/controller/InformQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamBoardCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamBoardReplyCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/TeamBoardDTO.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/TeamBoardDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamBoardQueryController.java
Labels: refactor

#194 feat: 팀스페이스 생성 및 조회
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamSpaceCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/TeamSpaceService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamSpaceRepository.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamSpaceQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/mapper/TeamSpaceQueryMapper.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/TeamSpaceQueryService.java
  src/main/resources/mapper/teamSpace/TeamSpaceMapper.xml
Labels: feat

#220 chore: 엘라스틱서치 노리분석기 적용, yml 수정
  Dockerfile
  docker-compose.yml
Labels: chore

#222 fix: 프로모션 종류 추가로 인한 프로모션 목록 조회 mapper.xml 수정
  src/main/resources/mapper/promotion/PromotionMapper.xml
Labels: fix

#226 feat: 상품 필터링 조건으로 목록 조회 기능 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsFilterReqDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/mapper/goods/GoodsMapper.xml
Labels: feat

#228 refactor: 프로모션 등록 수정
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
  src/main/resources/mapper/noti/NotiMapper.xml
Labels: refactor

#229 Feat: 프로모션 비교 분석 기능 구현
  src/main/java/com/beauty4u/backend/analysis/query/controller/AnalysisQueryController.java
  src/main/java/com/beauty4u/backend/analysis/query/dto/response/AnalysisAgeGroupRadioResDTO.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindComToPrevPromoGoodsSalesRankResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByComparisonSalesResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByTypeResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByYearSalesResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionStatisticalMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryService.java
  src/main/resources/mapper/analysis/analysisMapper.xml
  src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
  src/test/java/com/beauty4u/backend/analysis/query/service/AnalysisQueryServiceTest.java
  src/test/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryServiceTest.java
Labels: feat

#233 feat: 날짜별 상품 매출 증가, 하락률 구현
  docker-compose.yml
  src/main/java/com/beauty4u/backend/common/aggregate/PeriodType.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/goods_rate/query/controller/GoodsRateQueryController.java
  src/main/java/com/beauty4u/backend/goods_rate/query/dto/GoodsRateQueryDTO.java
  src/main/java/com/beauty4u/backend/goods_rate/query/dto/GoodsRateResDTO.java
  src/main/java/com/beauty4u/backend/goods_rate/query/mapper/GoodsRateQueryMapper.java
  src/main/java/com/beauty4u/backend/goods_rate/query/service/GoodsRateQueryService.java
  src/main/resources/mapper/goods/GoodsRateMapper.xml
Labels: feat, chore

#234 refactor: 프로모션 상세 조회, 적용 상품 조회 수정
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsListResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionDetailResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
  src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
  src/main/resources/mapper/promotion/PromotionMapper.xml
Labels: refactor

#238 chore: 날짜별 매출 증감률 조회 수정
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/mapper/goods/GoodsRateMapper.xml
Labels: chore

#231 docs: 기술 스택 작성
  readme.md
Labels: docs

#240 refactor: 일정 등록 리팩토링
  src/main/java/com/beauty4u/backend/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/beauty4u/backend/schedule/command/application/dto/CreateScheduleReqDTO.java
  src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleInfo.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/service/ScheduleDomainService.java
Labels: refactor

#245 fix: 지금까지의 오류 수정
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsSalesQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsFilterReqDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsSalesQueryService.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionGoodsQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsCommonInfoResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionGoodsSalesDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionGoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionGoodsQueryService.java
  src/main/resources/mapper/goods/GoodsMapper.xml
  src/main/resources/mapper/promotion/PromotionGoodsMapper.xml
  src/main/resources/mapper/promotion/PromotionMapper.xml
Labels: fix

#246 Refactor: 프로모션 통계 분석 검색 기능 구현
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionReqDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionTypeResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionStatisticalMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryService.java
  src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
Labels: refactor

#248 chore: 엘라스틱 서치 커스튬 적용
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
  src/main/resources/elasticsearch/mappings/mappings.json
  src/main/resources/elasticsearch/settings/settings.json
  src/main/resources/mapper/goods/GoodsRateMapper.xml
Labels: chore

#251 chore: 상품 목록 조회 페이징 처리 추가
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsListResDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/resources/mapper/goods/GoodsMapper.xml
Labels: chore

#254 refactor: 일정 등록시 SSE 알림 발송되도록 리팩토링
  src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
  src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
  src/main/java/com/beauty4u/backend/noti/command/domain/service/NotiDomainService.java
  src/main/java/com/beauty4u/backend/noti/query/controller/NotiQueryController.java
  src/main/java/com/beauty4u/backend/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
  src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
  src/main/resources/mapper/noti/NotiMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
Labels: refactor

#252 refactor: userList 페이징 처리 로직 리팩토링
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
  src/main/java/com/beauty4u/backend/user/query/controller/UserQueryController.java
  src/main/java/com/beauty4u/backend/user/query/dto/UserListDTO.java
  src/main/java/com/beauty4u/backend/user/query/dto/UserListResDTO.java
  src/main/java/com/beauty4u/backend/user/query/mapper/UserQueryMapper.java
  src/main/java/com/beauty4u/backend/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/UserMapper.xml
  src/test/java/com/beauty4u/backend/user/query/service/UserQueryServiceTest.java
Labels: refactor

#256 refactor: 자신의 문의만 수정하도록 변경
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/util/CustomUserUtil.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryDomainService.java
Labels: refactor

#260 refactor: 프로모션 분석 그래프 기능 리팩토링 완료
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByYearSalesResDTO.java
  src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
Labels: refactor

#262 feat: QnA 답변 로직 추가 및 리팩토링
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/controller/InquiryReplyCommandController.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyService.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/aggregate/InquiryReply.java
  src/main/java/com/beauty4u/backend/inquiry/command/domain/service/InquiryReplyDomainService.java
  src/main/java/com/beauty4u/backend/inquiry/query/controller/InquiryReplyQueryController.java
  src/main/java/com/beauty4u/backend/inquiry/query/dto/InquiryReplyResDTO.java
  src/main/java/com/beauty4u/backend/inquiry/query/mapper/InquiryReplyQueryMapper.java
  src/main/java/com/beauty4u/backend/inquiry/query/service/InquiryReplyQueryService.java
  src/main/resources/mapper/inquiry/InquiryReplyMapper.xml
Labels: feat, refactor

#266 chore: 상품 분석 조회 위한 상품 코드 추가
  src/main/java/com/beauty4u/backend/goods_rate/query/dto/GoodsRateQueryDTO.java
  src/main/resources/mapper/goods/GoodsRateMapper.xml
Labels: chore

#268 refactor: 공지사항 등록, 수정, 삭제 권한 설정
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionQueryService.java
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
Labels: refactor

#271 chore: 상품 분석 조회 위한 상품 코드 개수 삭제
  src/main/resources/mapper/goods/GoodsRateMapper.xml
Labels: chore

#269 refactor: 프로모션 분석 페이지 구현 #243
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionStatisticalQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByComparisonResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByGoodsSalesResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionStatisticalMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionStatisticalQueryService.java
  src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
Labels: refactor

#272 feat: 팀스페이스 명칭 채팅방으로 수정
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/file/command/application/dto/FileDTO.java
  src/main/java/com/beauty4u/backend/file/command/domain/service/FileDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatRoomCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/TeamSpaceCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatroom/CreateChatRoomReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatroom/FindChatRoomDTO.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/folder/FindFolderDTO.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatRoomService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/FolderService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/TeamSpaceService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatRoom.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/Folder.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/LastRead.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMessageRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatRoomRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/FolderRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/TeamSpaceRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatRoomDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/FolderDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/TeamspaceDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatRoomQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/TeamSpaceQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatMessage/ChatMessageResDto.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatroom/ChatRoomDetailsDto.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatroom/ChatRoomResponse.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatroom/ChatRoomUserInfoDto.java
  src/main/java/com/beauty4u/backend/teamspace/query/mapper/ChatRoomQueryMapper.java
  src/main/java/com/beauty4u/backend/teamspace/query/mapper/TeamSpaceQueryMapper.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/ChatQueryService.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/ChatRoomQueryService.java
  src/main/resources/mapper/teamSpace/ChatRoomMapper.xml
  src/main/resources/mapper/teamSpace/TeamSpaceMapper.xml
  src/main/resources/mapper/teamSpace/folder/FolderMapper.xml
  src/main/resources/mapper/teamSpace/teamboard/TeamBoardMapper.xml
Labels: feat, refactor

#277 refactor: 파일 업로드 리팩토링
  src/main/java/com/beauty4u/backend/file/command/application/controller/FileController.java
  src/main/java/com/beauty4u/backend/file/command/application/dto/FileDTO.java
  src/main/java/com/beauty4u/backend/file/command/domain/aggregate/FileInfo.java
  src/main/java/com/beauty4u/backend/file/command/domain/aggregate/FileType.java
  src/main/java/com/beauty4u/backend/file/command/domain/repository/FileRepository.java
  src/main/java/com/beauty4u/backend/file/command/domain/service/FileDomainService.java
Labels: refactor

#278 feat: 프로모션 알림 CRUD #273
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionNotiController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionNotiDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/UpdatePromotionNotiDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionNotiService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/aggregate/PromotionNoti.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionNotiRepository.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
Labels: feat

#281 feat: 채팅방 생성, 초대 및 파일 전송 기능 추가
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatMemberCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatRoomCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatroom/CreateChatRoomReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatroom/InviteUsersToChatRoomReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatMemberService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatRoomService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMember.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatRoom.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMemberRepository.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatRoomQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatMessage/ChatMessageResDto.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatroom/ChatRoomDetailsDto.java
  src/main/java/com/beauty4u/backend/teamspace/query/mapper/ChatRoomQueryMapper.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/ChatQueryService.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/ChatRoomQueryService.java
  src/main/java/com/beauty4u/backend/user/command/domain/repository/UserRepository.java
  src/main/resources/mapper/teamSpace/ChatRoomMapper.xml
Labels: feat, refactor

#286 feat: 특정 게시글에 업로드 된 파일 목록 조회
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/file/command/application/controller/FileController.java
  src/main/java/com/beauty4u/backend/file/query/controller/FileQueryController.java
  src/main/java/com/beauty4u/backend/file/query/dto/FileListReqDTO.java
  src/main/java/com/beauty4u/backend/file/query/dto/FileListResDTO.java
  src/main/java/com/beauty4u/backend/file/query/mapper/FileQueryMapper.java
  src/main/java/com/beauty4u/backend/file/query/service/FileQueryService.java
  src/main/resources/mapper/file/FileMapper.xml
  src/main/resources/mapper/teamSpace/teamboard/TeamBoardMapper.xml
Labels: feat, refactor

#279 feat: 프로모션 알림 기능 구현
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionNotiController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionNotiService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/repository/PromotionNotiRepository.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionNotiQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByCustomerGoodsResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByCustomerListResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
  src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
Labels: feat

#283 feat: 제미나이 리뷰 요약 기능 추가
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/config/gemini/GeminiRestTemplateConfig.java
  src/main/java/com/beauty4u/backend/goods/command/domain/repository/ReviewRepository.java
  src/main/java/com/beauty4u/backend/goods/query/controller/ReviewAiQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GeminiRequestDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GeminiResponse.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GeminiReviewResDTO.java
  src/main/java/com/beauty4u/backend/goods/query/service/GeminiReviewQueryService.java
Labels: feat

#292 Feat: 프로모션 알림 이메일 발송 기능 구현
  src/main/java/com/beauty4u/backend/common/util/MailUtil.java
  src/main/java/com/beauty4u/backend/config/mail/AsyncConfig.java
  src/main/java/com/beauty4u/backend/config/mail/MailConfig.java
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionNotiController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/PromotionEmailResult.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionNotiService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionNotiTargetResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
  src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
Labels: feat

#289 feat: 연관분석 연결 및 클라이언트 응답 dto 추가
  build.gradle
  src/main/java/com/beauty4u/backend/BackendApplication.java
  src/main/java/com/beauty4u/backend/analysis/command/application/controller/AprioriController.java
  src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriRequest.java
  src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResDTO.java
  src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResponse.java
  src/main/java/com/beauty4u/backend/analysis/command/application/service/AprioriService.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/AssociationRecommendation.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AnalysisRepository.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AssociationRecommendationRepository.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/service/AssociationRecommendationDomainService.java
  src/main/java/com/beauty4u/backend/analysis/command/infrastructure/flaskApi/AprioriClient.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/config/feignConfig/FeignConfiguration.java
  src/main/resources/application.yml
Labels: feat

#291 refactor: 제미나이 요약 리팩토링
  build.gradle
  src/main/java/com/beauty4u/backend/BackendApplication.java
  src/main/java/com/beauty4u/backend/analysis/command/application/controller/AprioriController.java
  src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriRequest.java
  src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResDTO.java
  src/main/java/com/beauty4u/backend/analysis/command/application/dto/AprioriResponse.java
  src/main/java/com/beauty4u/backend/analysis/command/application/service/AprioriService.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/aggregate/AssociationRecommendation.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AnalysisRepository.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/repository/AssociationRecommendationRepository.java
  src/main/java/com/beauty4u/backend/analysis/command/domain/service/AssociationRecommendationDomainService.java
  src/main/java/com/beauty4u/backend/analysis/command/infrastructure/flaskApi/AprioriClient.java
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/config/feignConfig/FeignConfiguration.java
  src/main/resources/application.yml
Labels: refactor

#294 feat: 채팅 CRUD 구현
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/file/command/application/dto/FileDTO.java
  src/main/java/com/beauty4u/backend/file/command/application/service/FileService.java
  src/main/java/com/beauty4u/backend/file/command/domain/service/FileDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatMemberCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatRoomCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatmember/ChatMemberReqDTO.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chatmember/ChatMemberResDTO.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatMemberService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatRoomService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMember.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMemberRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/repository/ChatMessageRepository.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatMemberDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatMessageDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/service/ChatRoomDomainService.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatRoomQueryController.java
  src/main/java/com/beauty4u/backend/teamspace/query/dto/chatroom/ChatRoomDTO.java
  src/main/java/com/beauty4u/backend/teamspace/query/mapper/ChatRoomQueryMapper.java
  src/main/java/com/beauty4u/backend/teamspace/query/service/ChatRoomQueryService.java
  src/main/resources/mapper/teamSpace/ChatRoomMapper.xml
Labels: feat, refactor

#295 feat: 같은 월에 대해서 해당연도와 지난연도의 연령별 매출을 조회하는 기능 추가
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsSalesQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsSalesAgeListFilterDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/GoodsSalesAgeListResDTO.java
  src/main/java/com/beauty4u/backend/goods/query/dto/MonthSalesDTO.java
  src/main/java/com/beauty4u/backend/goods/query/mapper/GoodsSalesQueryMapper.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsSalesQueryService.java
  src/main/resources/mapper/goods/GoodsSalesMapper.xml
Labels: feat

#297 feat: 이메일 전송 수정 #296
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
Labels: fix

#299 feature: 플라스크 연동 백엔드 기능 구현
  src/main/java/com/beauty4u/backend/analysis/command/application/controller/CollaboFilterController.java
  src/main/java/com/beauty4u/backend/analysis/command/application/dto/CollaboFilterResDTO.java
  src/main/java/com/beauty4u/backend/analysis/command/application/service/CollaboFilterService.java
  src/main/java/com/beauty4u/backend/analysis/command/infrastructure/flaskApi/CollaboFilter.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionNotiQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
  src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
Labels: feat

#301 feat, refactor: 깃허브 액션 리팩토링 및 배포 과정 추가
  .github/workflows/develop-pr-check.yml
  .github/workflows/main-deploy.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  elastic/Dockerfile
  src/main/resources/application.yml
Labels: feat, refactor

#303 feat: 채팅방 추가 및 유저 초대 CRUD
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatMemberCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/controller/ChatRoomCommandController.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/dto/chat/ChatMessageReqDto.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatMemberService.java
  src/main/java/com/beauty4u/backend/teamspace/command/application/service/ChatRoomService.java
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
  src/main/java/com/beauty4u/backend/teamspace/query/controller/ChatRoomQueryController.java
  src/main/resources/mapper/teamSpace/ChatRoomMapper.xml
Labels: feat, chore

#311 chore: 쿼리 수정 및 DTO 수정
  src/main/java/com/beauty4u/backend/promotion/command/application/controller/PromotionNotiController.java
  src/main/java/com/beauty4u/backend/promotion/command/application/service/PromotionNotiService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionByComparisonResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
  src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
Labels: chore
