Repository code-4-u/beauty-4-u-BE, pull requests merged in 2025-01, with the labels that each got.

#302 refactor: 깃허브 액션 수정
  .github/workflows/develop-pr-check.yml
  .github/workflows/main-deploy.yml
Labels: refactor

#305 chore: yml 파일 설정 추가
  src/main/resources/application.yml
Labels: chore

#313 refactor: 프로모션 알림, QnA 알림, 프로모션 등록 오류 해결, 알림 모두 삭제 기능 추가
  src/main/java/com/beauty4u/backend/common/exception/ErrorCode.java
  src/main/java/com/beauty4u/backend/common/success/SuccessCode.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/dto/QnaReplyReqDTO.java
  src/main/java/com/beauty4u/backend/inquiry/command/application/service/InquiryReplyService.java
  src/main/java/com/beauty4u/backend/noti/command/application/controller/NotiCommandController.java
  src/main/java/com/beauty4u/backend/noti/command/application/dto/NotiIdReqDTOList.java
  src/main/java/com/beauty4u/backend/noti/command/application/service/NotiService.java
  src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
  src/main/java/com/beauty4u/backend/noti/command/domain/repository/NotiRepository.java
  src/main/java/com/beauty4u/backend/noti/command/domain/service/NotiDomainService.java
  src/main/java/com/beauty4u/backend/promotion/command/application/dto/SavePromotionReqDTO.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
  src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleInfo.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/aggregate/ScheduleType.java
  src/main/java/com/beauty4u/backend/schedule/command/domain/service/ScheduleDomainService.java
  src/main/java/com/beauty4u/backend/user/command/domain/service/UserDomainService.java
Labels: fix, feat, refactor

#321 refactor: 엘라스틱서치 오픈서치로 마이그레이션
  build.gradle
  logstash/Dockerfile
  logstash/pipeline/logstash.conf
  src/main/java/com/beauty4u/backend/elasticsearch/BaseSearchDocument.java
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchConfig.java
  src/main/java/com/beauty4u/backend/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/com/beauty4u/backend/goods/query/controller/GoodsQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/controller/ReviewQueryController.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/GoodsDocument.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/document/ReviewDocument.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/GoodsSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/elasticsearch/repository/ReviewSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/opensearch/document/GoodsDocument.java
  src/main/java/com/beauty4u/backend/goods/query/opensearch/repository/GoodsSearchRepository.java
  src/main/java/com/beauty4u/backend/goods/query/service/GoodsQueryService.java
  src/main/java/com/beauty4u/backend/goods/query/service/ReviewQueryService.java
  src/main/java/com/beauty4u/backend/opensearch/OpenSearchConfig.java
  src/main/java/com/beauty4u/backend/security/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: feat, refactor

#320 fix: 깃허브 빌드 문제 해결
  src/main/java/com/beauty4u/backend/teamspace/command/domain/aggregate/ChatMessage.java
Labels: fix

#322 fix: 매출율 조회 오류 해결
  src/main/resources/mapper/goods/GoodsRateMapper.xml
Labels: fix

#329 fix: 이메일 오류 수정 #328
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
Labels: fix

#331 chore: DTO mapper 수정 #330
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionReqDTO.java
  src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
Labels: chore

#333 chore: mapper 수정 #332
  src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
Labels: chore

#335 refactor: 페이징 처리 적용 #334
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionNotiQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionListResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
  src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
Labels: refactor

#337 deploy: 배포 2차
  src/main/java/com/beauty4u/backend/common/util/MailUtil.java
  src/main/java/com/beauty4u/backend/noti/command/domain/aggregate/NotiType.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionDomainService.java
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionNotiQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/controller/PromotionTypeQueryController.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionListResDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/FindPromotionReqDTO.java
  src/main/java/com/beauty4u/backend/promotion/query/dto/PromotionTypeList.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionNotiQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/mapper/PromotionTypeQueryMapper.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionNotiQueryService.java
  src/main/java/com/beauty4u/backend/promotion/query/service/PromotionTypeQueryService.java
  src/main/java/com/beauty4u/backend/schedule/command/application/service/ScheduleService.java
  src/main/resources/mapper/promotion/PromotionNotiQueryMapper.xml
  src/main/resources/mapper/promotion/PromotionStatisticalMapper.xml
  src/main/resources/mapper/promotion/PromotionTypeMapper.xml
Labels: chore

#339 chore: 전송 이메일 추가 #338
  src/main/java/com/beauty4u/backend/promotion/command/domain/service/PromotionNotiDomainService.java
Labels: chore
